WebApplication1/Controllers/ForumController.cs
using CodeKicker.BBCode;
using Insurance.Domaine.Entity;
using Insurance.Service;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ForumController : Controller
    {
        TopicService Ts = new TopicService();
        SousCategoryService Ss = new SousCategoryService();
        UserService Us = new UserService();
        CategoryService Cs = new CategoryService();
        FavorisService Fs = new FavorisService();
        MessagesService Ms = new MessagesService();
        ReponseService Rs = new ReponseService();
        LikesService Ls = new LikesService();
        FilterService sfil = new FilterService();

        public static users currentuser= new users();
        public static List<users> userss = null;
        public static string msg = "";
        public static string msg2 = "";





        // GET: Forum
        public ActionResult First()
        {
            var client = new RestClient("http://localhost:18080/insurance-web/api/");
            var request = new RestRequest("Category", Method.GET);
            request.AddHeader("Content-type", "application/json");
            IRestResponse<List<category>> Cat = client.Execute<List<category>>(request);


            ViewBag.topic = Ts.GetAll();
            ViewBag.soucategory = Ss.GetAll();
            ViewBag.message = Ms.GetAll();
            ViewBag.user = Us.GetAll();


            return View(Cs.GetAll());
        }



        public void DeleteMessage(int id)
        {
            messages m = Ms.GetById(id);
            Ms.Delete(m);
            Ms.Commit();
        }

        public ActionResult AddFavoris(int id , int iduser, int idcat)
        {

            if (iduser==0)
            {
                msg= "Sorry, you have to connect";
                return RedirectToAction("Login");
            }
            else { 
            var listf = Fs.GetAll();
            favoris f = new favoris();
            f.idtopic = id;
            f.iduser = iduser;

            f.date = DateTime.Now;

            Fs.Add(f);
            Fs.Commit();
            return RedirectToAction("ViewForum", new
            {
          id=idcat
            });

            }
        }


        public ActionResult AddFavoris2(int id, int iduser)
        {

            if (iduser == 0)
            {
                msg = "Sorry, you have to connect";
                return RedirectToAction("Login");
            }
            else
            {
                var listf = Fs.GetAll();
                favoris f = new favoris();
                f.idtopic = id;
                f.iduser = iduser;

                f.date = DateTime.Now;

                Fs.Add(f);
                Fs.Commit();
                return RedirectToAction("ViewTopic", new
                {
                    id = id,
                    idRep = 0,
                });

            }
        }



        public ActionResult AddLike(int id, int iduser)
        {

            if (iduser == 0)
            {
                msg = "Sorry, you have to connect";
                return RedirectToAction("Login");
            }
            else
            {
                var listf = Ls.GetAll();
                likes l = new likes();
                l.idmessage = id;
                l.iduser = iduser;

                l.date = DateTime.Now;
                messages messages = Ms.GetById(id);
                messages.nbLike = messages.nbLike + 1;
                Ms.Update(messages);
                Ms.Commit();


                Ls.Add(l);
                Ls.Commit();
                return RedirectToAction("ViewTopic", new
                {
                    id = messages.topic.idTopic,
                    idRep = id,
                });

            }
        }



        public ActionResult Deletelike(int id, int iduser)
        {

            if (iduser == 0)
            {
                msg = "Sorry, you have to connect";
                return RedirectToAction("Login");
            }
            else
            {
       
                var listf = Ls.GetAll();
                likes l = new likes();
                foreach (var item in listf)
                {
                    if (item.idmessage == id && item.iduser == iduser)
                    {
                        l = item;
                    }
                }

                messages messages = Ms.GetById(id);
                messages.nbLike = messages.nbLike - 1;
                Ms.Update(messages);
                Ms.Commit();


                Ls.Delete(l);
                Ls.Commit();
                return RedirectToAction("ViewTopic", new
                {
                    id = messages.topic.idTopic,
                    idRep = id,
                });

            }
        }




      
        



        public ActionResult DeleteFavoris(int id, int iduser)
        {

            if (iduser == 0)
            {
                msg = "Sorry, you have to connect";
                return RedirectToAction("Login");
            }
            else
            {
                var listf = Fs.GetAll();
                   favoris f = new favoris();
                foreach (var item in listf)
                {
                    if  (item.idtopic==id && item.iduser==iduser)
                    {
                        f = item;
                    }
                }


                Fs.Delete(f);
                Fs.Commit();
              
                return RedirectToAction("ViewTopic", new
                {
                    id = id,
                idRep=0,
                });

            }
        }


        public ActionResult ViewForum(int id)
        {
            ViewBag.message = Ms.GetAll();
            ViewBag.idcategory = id;
            ViewBag.topic = Ts.GetAll();
            ViewBag.soucategory = Ss.GetAll();
            ViewBag.user = Us.GetAll();
            ViewBag.lastpost= Ms.LastPost();
            ViewBag.fav = Fs.GetAll();

            return View(Ss.GetAll());
        }

        public ActionResult AddTopic()
        {

            ViewBag.topic = Ts.GetAll();
            ViewBag.soucategory = Ss.GetAll();
            ViewBag.user = Us.GetAll();

            return View(Ss.GetAll());


            return View();
        }
        [HttpPost]
        public ActionResult AddTopic(HttpPostedFileBase photo)
        {
            try
            {
                var sujet = Request.Form["subject"];

                var contenu = Request.Form["message"];
                    
                var soucat = Request.Form["subject1"];
                var x=Ss.getByName(soucat);

                var top = new topic();

                top.contenu = (sujet); 
                top.sujet = (contenu);

                var restClient = new RestClient("http://localhost:18080/insurance-web/api/");
                restClient.AddDefaultHeader("accept", "*/*");
                var request = new RestRequest("Topic?id="+x[0].idSousCategory, Method.POST);
                request.AddJsonBody(new
                {

                    sujet = sujet,
                    contenu = contenu
                });
                var response = restClient.Execute(request);
                return RedirectToAction("First");

            }
            catch (Exception ex)
            {
                ViewBag.Message = "ERROR:" + ex.Message.ToString();
                return RedirectToAction("AddTopic");
            }
        }



        public ActionResult ViewTopic(int id, int idRep)
        {
            ViewBag.message = Ms.GetAll();
            ViewBag.reponse = Rs.GetAll();
            ViewBag.idtopic= id;
            ViewBag.topic = Ts.GetAll();
            ViewBag.soucategory = Ss.GetAll();
            ViewBag.user = Us.GetAll();
            ViewBag.fav = Fs.GetAll();
            ViewBag.idRep = idRep;
            ViewBag.likes = Ls.GetAll() ;
            ViewBag.msg = msg2;
            msg2 = "";

                

            return View();
        }


        [HttpPost]
        public ActionResult ViewTopic(int id)
        {

            var filtre = sfil.GetAll();
            int i = 0;
            bool verif = false;
            var contenu = Request.Form["message"];
            var message = new topic();
            message.contenu = (contenu);

            foreach (var item in filtre)
            {
                if (message.contenu.Contains(item.text))
                {
                    verif = true;
                }
            }


            if (!verif)
            {
                try
                {
                    var restClient = new RestClient("http://localhost:18080/insurance-web/api/");
                    restClient.AddDefaultHeader("accept", "*/*");
                    var request = new RestRequest("Message?idtopic=" + id, Method.POST);
                    request.AddJsonBody(new
                    {

                        contenu = contenu

                    });
                    var response = restClient.Execute(request);

                }

                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    return RedirectToAction("AddTopic");
                }



                List<messages> messages = (List<messages>)Ms.GetAll();
                int count = messages.Count() - 1;

                int idRep = messages[count].idMessage;

                return RedirectToAction("ViewTopic", new
                {
                    id = id,
                    idRep = idRep,
                });
            }
            else
            {
                msg2 = "verifier votre language!!!!";
                return RedirectToAction("ViewTopic", new
                {
                    id = id,
                    idRep = 0,
                });

WebApplication1/Views/Forum/First.cshtml
@using WebApplication1.Models
@using Insurance.Domaine.Entity
@using WebApplication1.Controllers
@model IEnumerable<Insurance.Domaine.Entity.category>


@{
    Layout = null;
    List<topic> topics = (List<topic>)ViewBag.topic;
    List<souscategory> souscategories = (List<souscategory>)ViewBag.soucategory;
    List<users> users = (List<users>)ViewBag.user;
    List<messages> messages = (List<messages>)ViewBag.message;
    users currentUser = ForumController.currentuser;
    List<users> usersconnected = ForumController.userss;


}




<html>


<head>
    <link rel="alternate" type="application/atom+xml" title="Feed - Gramziu Themes" href="feed.php" />
    <link rel="alternate" type="application/atom+xml" title="Feed - New Topics" href="feed9d17.php?mode=topics" />
    <link rel="apple-touch-icon-precomposed" href="styles/ariki/theme/images/apple-touch-icon-precomposed.gif">
    <link rel="icon" href="styles/ariki/theme/images/favicon.gif" />
    <link rel="icon" sizes="16x16" href="styles/ariki/theme/images/favicon.ico" />
    <link href="~/Front/Forum/maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="screen, projection" />
    <link href="~/Front/Forum/styles/ariki/theme/stylesheet6148.css" rel="stylesheet" type="text/css" media="screen, projection" />
    <link href="~/Front/Forum/styles/ariki/theme/colours6148.css" rel="stylesheet" type="text/css" media="screen, projection" />

</head>
<body id="phpbb" class="nojs notouch section-index ltr  " style="background-color: #eaecf0">
    <table style="background-color: black; width: 100%">
        <div class="row">

            <tr>
                <td style="padding-left: 20px;">
                    <img src="~/Front/Forum/images/logo.png" style="height: 20px; padding-left: 10px; margin-top: 5px">

                </td>
                <td>
                    <img src="~/Front/Forum/images/black.png" style="height: 20px; padding-left: 80px; margin-top: 5px">

                </td>

                <td>
                    <img src="~/Front/Forum/images/social.png " style="height: 30px ; margin-top: 5px">

                </td>
                <td>
                    <img src="~/Front/Forum/images/black.png" style="height: 20px; padding-left: 60px; margin-top: 5px">

                </td>

                @if (currentUser.id==0)
                {



                <td style="width: 2px">
                    <img src="~/Front/Forum/images/m.png" style="height: 15px ">

                </td>

                <td class="top-bar">
                    <ul class="tools">
                        <li>
                            <a href="~/Forum/Login">
                                <span class="hidden-md" style="font-size: 10px">Se connecter!</span>
                            </a>
                        </li>
                    </ul>
                </td>
                }
                else
                { 
                <td class="top-bar">
                    <ul class="tools">
                        <li>
                            <a href="#">
                                <span class="hidden-md" style="font-size: 10px">Bonjour,@currentUser.login</span>
                                
                            </a>
                            |
                            <a href="@Url.Action("Logout")">
                                <span class="hidden-md" style="font-size: 10px">LogOut</span>

                            </a>
                        </li>
                    </ul>
                </td>
                }



            </tr>
        </div>
    </table>

    <div id="wrap-body">
        <div id="wrap-subhead-main">
            <div class="chunk">
                <div class="wrap-subhead-main">


                    <ul id="breadcrumbs-main" role="menubar">

                        <li class="font-icon responsive-menu dropdown-container" data-skip-responsive="true" style="margin-top:10px">
                            <a href="#" class="responsive-menu-link dropdown-trigger dropdown-toggle"><i class="fa fa-bars"></i></a>
                            <div class="dropdown hidden">
                                <div class="pointer"><div class="pointer-inner"></div></div>
                                <ul class="dropdown-contents" role="menu">

                                    <li class="separator"></li>
                                    <li class="font-icon icon-search-unanswered"><a href="" role="menuitem"><i class="fa fa-file-o"></i>Unanswered posts</a></li>
                                    <li class="font-icon icon-search-active"><a href="./search.php?style=3&amp;search_id=active_topics" role="menuitem"><i class="fa fa-fire"></i>Active topics</a></li>
                                    <li class="separator site-menu"></li>

                                    <li data-skip-responsive="true" class="site-menu"><a href="./faq.php?style=3" rel="help" title="Frequently Asked Questions">FAQ</a></li>
                                    <li class="site-menu">
                                        <a href="#" title="Example">Drop Down</a>
                                        <ul>
                                            <li><a href="#">Lorem ipsum</a></li>
                                            <li><a href="#">Welcome to phpBB3</a></li>
                                            <li><a href="#">Frequently Asked Questions</a></li>
                                            <li><a href="#">BBCode example</a></li>
                                        </ul>
                                    </li>

                                </ul>
                            </div>
                        </li>

                        <li class="breadcrumbs rightside">
                            <span class="crumb"><a href=" path('list_categorie" accesskey="h" itemtype="http://data-vocabulary.org/Breadcrumb" itemscope="" data-navbar-reference="index" title="Board index"><i class="fa fa-home"></i>
                                <span>Forum</span></a></span>
                        </li>
                    </ul>


                </div>
            </div>
        </div>
        <div class="chunk">



             
            @foreach (var item in Model)
            {

                <div class="forabg" style="background-color: black!important;">



                    <div class="inner">
                        <ul class="topiclist">
                            <li class="header">
                                <dl class="icon">
                                    <dt>
                                        <div class="list-inner">
                                            <a href="@Url.Action("ViewForum", new {id = item.idCategory})">
                                                @item.NameCategory
                                            </a>
                                        </div>
                                    </dt>
                                    <dd class="topics">Topics</dd>
                                    <dd class="posts">Reponse</dd>
                                    <dd class="lastpost">Derniére Reponse</dd>
                                </dl>
                             </li>
                        </ul>
                        @foreach (var souscat in souscategories)
                        {
                            if (item.idCategory == souscat.category.idCategory)
                            {





                        <!--sous categorie -->

                                <ul class="topiclist forums">

                                    <li class="row">
                                        <dl class="icon global_read">
                                            <dt title="No unread posts">

                                                <div class="list-inner">
                                                    <a href="" class="forumtitle">
                                                        @souscat.Name
                                                    </a> <br /> <a href=""> </a>
                                                    @{ int nbtopic = 0;}
                                                    @foreach (var top in topics)
                                                    {
                                                        if (top.souscategory.idSousCategory == souscat.idSousCategory)
                                                        {

                                                            nbtopic = nbtopic + 1;



                                                            <a href="@Url.Action("ViewTopic", new {id = top.idTopic, idRep=0})">
                                                                <small>@top.sujet</small>

                                                                ,
                                                            </a>

                                                        }
                                                    }

                                                    <div class="responsive-show" style="display: none;">
                                                        Sujets: <strong>longeur123</strong>
                                                    </div>
                                                </div>
                                            </dt>


                                            <dd class="topics">
                                               
      
                                                @nbtopic                                          
                                                      <dfn>Topics</dfn>
                                            </dd>
                                            @{ int nbmsg = 0;}
                                            @foreach (var msg in messages)
                                            {
                                                if (msg.topic.souscategory.idSousCategory == souscat.idSousCategory)
                                                {
                                                    nbmsg = nbmsg + 1;
                                                }
                                            }


                                            <dd class="posts">
                                               @nbmsg

                                                <dfn>Posts</dfn>
                                            </dd>
                                            <dd class="lastpost">
                                                <dfn>Last post</dfn>
                                                <a href="viewtopic3608.html?style=3&amp;f=7&amp;p=70#p70"
                                                   title="Re: Sample" class="lastsubject">Re: Sample</a> <br />
                                                by <a href="memberlist8198.html?style=3&amp;mode=viewprofile&amp;u=51"
                                                      class="username">Oualha</a> 07 Dec 2015, 20:20
                                            </dd>
                                        </dl>
                                    </li>
                                </ul>
                            }
                        }


                    </div>


                </div>
            }

            </br></br>





            @{ int connected = 0;}
            @if (currentUser.id!=0)
            {
               
            }

            <div class="stat-block online-list">
                <h3>Qui est en Ligne?</h3>
                <p>
                    Au total, il y a
                    <strong> 1</strong>
                    Utilisateur(s) en Ligne :

                    <br />

                    <br />
                   

                    Utlisateur(s) Enregistrés:
                    @foreach (var u in users)
                    {
                        <a>
                            @u.login
                            ,
                        </a>
                    }

                    <br />

                    <em>
                        Legend:
                        <a style="color:#AA0000" href="memberlistd454.html?style=3&amp;mode=group&amp;g=5">Administrators</a>, <a style="color:#00AA00" href="memberlist548f.html?style=3&amp;mode=group&amp;g=4">Insured</a>, <span style="color:#9E8DA7"> Company Agent </ span >, <a href="memberlistdddb.html?style=3&amp;mode=group&amp;g=2">Expert</a>
                    </em>
                </p>
                <p id="online-list-stat">
                    Total sous-categories<strong> @souscategories.Count()</strong> &bull; Total topics<strong> @topics.Count()</strong> &bull; Total members<strong>@users.Count()</strong> &bull; Our newest member <strong><a href="memberlistf184.html?style=3&amp;mode=viewprofile&amp;u=1114" class="username">Oualha</a></strong>
                </p>
            </div>





        </div>

    </div>


    </div>
    </div>






    <script type="text/javascript" src="~/Front/Forum/assets/javascript/editor.js~/Front/"></script>


    <script type="text/javascript" src="~/Front/Forum/styles/ariki/template/forum_fn.js?assets_version=174.js')"></script>

    <script type="text/javascript" src="~/Front/Forum/styles/ariki/template/ajax6148.js')"></script>

    <script type="text/javascript" src="~/Front/Forum/styles/ariki/template/chosen.jquery.min6148.js')"></script>




</body>










</html>

WebApplication1/Views/Forum/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = null;
}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>
    <!-- Bootstrap core CSS-->
    <link href="~/Front/User/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/Front/User/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="~/Front/User/css/sb-admin.css" rel="stylesheet">
</head>

<body class="bg-dark">

    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Login</div>
            <div class="card-body">
                <form method="post">
                    <p style="color:red">
                        @ViewBag.ErrorMessage
                    </p>

@using (Html.BeginForm("Login", "Forum", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
   

                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input class="form-control" name="login" id="login"  aria-describedby="emailHelp" placeholder="Enter login">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input class="form-control" name="password" id="password" type="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox"> Remember Password
                            </label>
                        </div>
                    </div>
                    <input type="submit" value="Login" class="btn btn-primary btn-block" />
}
                </form>
                <div class="text-center">
                    <a class="d-block small mt-3" href="~/Front/User/register.html">Register an Account</a>
                    <a class="d-block small" href="~/Front/User/forgot-password.html">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
</body>

</html>